#file: noinspection YAMLSchemaValidation
spring:
  application:
    name: mp-study
  datasource:
    url: jdbc:mysql://localhost:3306/my-study?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    me.fengqizihang: debug
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  type-aliases-package: me.fengqizihang.mpstudy.pojo # 扫描实体类所在的包
  global-config:
    db-config:
      id-type: auto # 主键策略，auto表示数据库自增
